# Site settings
title: Hala Haddad

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/hala-haddad-3577762b/
   
 - title: Email
   url: mailto:h.m.haddad@gmail.com

#Any buzzword skills you want to include
skills:
 - Ruby
 - Ruby on Rails
 - JavaScript
 - React
 - HTML5
 - CSS3
 - Java

#Work experience is required
roles:
 - title: Student
   start: 2020
   end: ongoing
   employer: Ada Developers Academy
   description: In the process of learning how to become a full stack engineer.

 - title: Instructor
   start: 2011
   end: 2014
   employer: An-Najah National University
   description: Taught and developed curriculum for the following courses, Environmental systems in architecture, Solar energy in architecture, History of architecture, Theory of architecture, Human behavior in architecture, Introduction to sustainable design.

 - title: Project Manger/Coordinator
   start: 2011
   end: 2012
   employer: Partners for Sustainable Development PSD
   description: Managed and coordinated educational sustainability project, NETKETABI. Organized and led 50 public workshops on social and community development. Recruited 25 schools and public and local institutions to adapt NETKETABI, and expanded PSD partnership to include more than 17 rural communities. Organized fundraising events for non-profit, and was in charge of budgeting and accounting for different sustainable projects in my responsibility

 - title: Teaching Assistant
   start: 2010
   end: 2008
   employer: The Pennsylvania State University "Penn State"
   description: TA for the following courses. Architecture design analyses, Studies in principles and elements of design, planning for human use, The relationship of space to physical to physical and social environment, Architectural design analysis inspection, visual communications, basic design studio
   
 - title: Design Instructor
   start: 2009
   end: 2010
   employer: The Pennsylvania State University "Penn State"
   description: Fulltime instructor for first year architecture design studio I & II
   
 - title: Architect
   start: 2005
   end: 2007
   employer: Al Ameed Consulting
   description: Drafted architectural and structural detailed documents, 3D renderings, and physical models of projects using Autocad, Photoshop, and 3D Max
      
#Education is required
education:
 - level: Masters of Architecture
   date: 2011
   subject: Sustainable Design and Development
   school: THE PENNSYLVANIA STATE UNIVERSITY, UNIVERSITY PARK, PA
  
 - level: Bachelor of Architecture 
   date: 2004
   subject: Architectural Engineering
   school: An Najah National University, Nablus, Palestine
  

#List of interesting Github repo/projects to include - optional
github:
 - halahaddad1/inspiration-board
 - halahaddad1/exquisite-react
 - halahaddad1/react-tic-tac-toe
 - halahaddad1/slack-cli
 - halahaddad1/hotel
 - halahaddad1/oo-ride-share

intro: 
Hala (she/her) has many years working in Architectural Sustainable Design, teaching Green Building Technologies, and Environmental Awarness in general. Hala has a Masters degree in Architecture from the Pennsylvania State University, and after many years working in her field, moving to Seattle sparked an interest in the exciting fast paced world of Software Engineering! Hala found numerous similarities within the creative process of Architects and Software Engineers, especially the need to understand space functionality, human behavior and flow within a design! and is excited to embark on a journey where she gets to learn a new set of skills and use Architectural creativity within a new medium.  
In her spare time Hala loves to spend quality time with her husband and two boys.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
   <strong>Ruby</strong>
   <strong>Ruby on Rails</strong>
   <strong>JavaScript</strong> 
   <strong>React</strong>
   <strong>HTML5</strong>
   <strong>CSS3</strong>
   <strong>Java</strong>
   <strong>Autodesk Autocad</strong>
   <strong>Autodesk REVIT</strong>
   <strong>Ecotect Analysis</strong>
   <strong>Green Building Studio</strong>
   <strong>Adobe Suite</strong>
   <strong>3D Studio Max</strong>


   
